title = "classical register without measure"

description = "If no quantum bit is measured, then no result should be produced."

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q1[1];
creg c0[4];
x q1[0];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[4] c0;
qubit q1;
x q1;
"""

cutoff = 0.9

result = []
