title = "dynamic circuit"

description = "circuit with condition"

qasm3 = """OPENQASM 3.0;
include "stdgates.inc";
bit[2] a;
qubit[1] q1;
h q1[0];
a[0] = measure q1[0];
if (!a[0]) {
  x q1[0];
}
a[1] = measure q1[0];
"""

cutoff = 0.9

compare_as_set = true

result = [
"10",
"11"
]
