title = "Measure into classical register twice"

description = "The second measurement result should shadow the first result."

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q1[4];
creg c0[2];
x q1[0];
x q1[3];
measure q1[0] -> c0[0];
measure q1[1] -> c0[0];
measure q1[2] -> c0[1];
measure q1[3] -> c0[1];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[2] c0;
qubit[4] q1;
x q1[0];
x q1[3];
c0[0] = measure q1[0];
c0[0] = measure q1[1];
c0[1] = measure q1[2];
c0[1] = measure q1[3];
"""

cutoff = 0.9

result = [
"10"
]
