title = "measure_all_reversed"

description = "measure all qubits with a single classical register in reversed order"

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
creg meas[4];

x q[0];

measure q[0] -> meas[3];
measure q[1] -> meas[2];
measure q[2] -> meas[1];
measure q[3] -> meas[0];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[4] meas;
qubit[4] q;

x q[0];

meas[3] = measure q[0];
meas[2] = measure q[1];
meas[1] = measure q[2];
meas[0] = measure q[3];
"""

cutoff = 0.9

result = [
    "1000"
]
