title = "no measurement"
description = "circuits without measurements should not produce any counts"

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q[4];
x q[0];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
qubit[4] q;
x q[0];
"""

cuttoff = 0.9

result = []

