title = "Only classical register"

description = "Simulator should not return result if no qubits are present."

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
creg c0[4];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[4] c0;
"""

cutoff = 0.9

result = []
