title = "Single qubit"

description = "Circuits with a single qubit should still be simulatable."

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[1] c0;
qubit q1;
x q1;
c0[0] = measure q1;
"""

cutoff = 0.9

result = [
"1"
]
