title = "Single result bit"

description = "Circuits with a single result bit should still be simulatable."

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit c0;
qubit[1] q1;
x q1[0];
c0 = measure q1[0];
"""

cutoff = 0.9

result = [
"1"
]
