title = "Sparse classical register"

description = "All unset bits of a classical register should be initialized as 0."

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q1[4];
creg c0[4];
x q1[0];
x q1[1];
x q1[2];
x q1[3];
measure q1[1] -> c0[1];
measure q1[3] -> c0[3];
"""

qasm3 = """OPENQASM 3;
include "stdgates.inc";
bit[4] c0;
qubit[4] q1;
x q1[0];
x q1[1];
x q1[2];
x q1[3];
c0[1] = measure q1[1];
c0[3] = measure q1[3];
"""

cutoff = 0.9

result = [
"1010"
]
