title = "Uniform superposition over multiple classical registers"

description = "All four register configurations must be recoverable!"

qasm2 = """OPENQASM 2.0;
include "qelib1.inc";
qreg q1[2];
creg a[1];
creg b[1];
h q1[0];
h q1[1];
measure q1[0] -> a[0];
measure q1[1] -> b[0];
"""

qasm3 = """OPENQASM 3.0;
include "stdgates.inc";
bit[1] a;
bit[1] b;
qubit[2] q1;
h q1[0];
h q1[1];
a[0] = measure q1[0];
b[0] = measure q1[1];
"""

cutoff = 0.9

compare_as_set = true

result = [
    "0 0",
    "1 0",
    "0 1",
    "1 1",
]
